-- ----------------------------------------------------------------------------
-- Put here INSERT statements for inserting data required by the application
-- in the "pojo" database. The primary keys are autogenerated.
-------------------------------------------------------------------------------


-----------------------------Categories------------------------------------------
INSERT INTO Category VALUES(null,'SmartPhones');
INSERT INTO Category VALUES(null,'VideoGames');


-----------------------------Products-------------------------------------------
--SmartPhones
INSERT INTO Product VALUES(null,1,'LG Nexus 4',299.00,'https://lh3.googleusercontent.com/-71rz-M__r-U/UVWU9dCAUgI/AAAAAAAAAF8/n97N0coS5_0/w506-h750/lg-nexus-4.jpg',0,0);
INSERT INTO Product VALUES(null,1,'Samsung Galaxy S4',649.00,'http://www.tuexperto.com/wp-content/uploads/2013/03/Samsung-Galaxy-S4-053.jpg',0,0);
INSERT INTO Product VALUES(null,1,'HTC One',499.00,'http://insideireland.ie/wp-content/uploads/2013/03/Xperia-Z.jpg',0,0);
INSERT INTO Product VALUES(null,1,'Sony Xperia Z',599.00,'http://www.htc.com/managed-assets/shared/desktop/smartphones/htc-one/hero/HTC-ProductDetail-Hero-slide-04.png',0,0);
INSERT INTO Product VALUES(null,1,'Iphone 5',669.00,'http://applezona.com/wp-content/uploads/2012/11/iphone-51.jpg',0,0);
INSERT INTO Product VALUES(null,1,'Samsung Galaxy Mega',749.00,'http://img.xataka.com/2013/06/Samsung%20Galaxy%20Mega%206.3.jpg',0,0);
INSERT INTO Product VALUES(null,1,'LG Optimus G',600.00,'http://www.puntogeek.com/wp-content/uploads/2013/04/LG-Optimus-G.jpg',0,0);
--VideoGames
INSERT INTO Product VALUES(null,2,'PlayStation 4',399.99,'http://es.playstation.com/media/55acuiVM/dualshock_system.jpg',0,0);
INSERT INTO Product VALUES(null,2,'Xbox One',499.99,'http://compass.xboxlive.com/assets/59/d5/59d51511-a3a1-42df-8f82-912b0a1e05cb.png?n=XBR_Hero2.png',0,0);
INSERT INTO Product VALUES(null,2,'Grand Theft Auto V',69.99,'http://thehut.pantherssl.com/productimg/0/600/600/86/10569986-1364980752-887226.jpg',0,0);
INSERT INTO Product VALUES(null,2,'Assassins Creed Black Flag',69.99,'http://www.blogcdn.com/www.joystiq.com/media/2013/02/ac4bfps3uk2d-1362054374.jpg',0,0);
INSERT INTO Product VALUES(null,2,'NBA 2K14',69.99,'http://i11a.3djuegos.com/juegos/10016/nba_2k14/fotos/ficha/nba_2k14-2276776.jpg',0,0);


-----------------------------UserProfiles----------------------------------------
INSERT INTO UserProfile VALUES(null,'mmontes11','NCJC/tk3ymYck','Martín','Montes','martin11lrx@gmail.com','5th Avenue',255,'3A',10000,0);
INSERT INTO UserProfile VALUES(null,'admin','TBQY4oiDqAK5M','admin','admin','admin@tendereteonline.com','0',0,'0',0,0); 	

-----------------------------Orders---------------------------------------------
INSERT INTO Ord VALUES(null,1,STR_TO_DATE('01,5,2013','%d,%m,%Y'));

-----------------------------OrderLines----------------------------------------
INSERT INTO OrderLine VALUES(null,1,1,1,10);
INSERT INTO OrderLine VALUES(null,2,1,1,10);
INSERT INTO OrderLine VALUES(null,3,1,1,10);
INSERT INTO OrderLine VALUES(null,4,1,1,10);
INSERT INTO OrderLine VALUES(null,5,1,1,10);
INSERT INTO OrderLine VALUES(null,6,1,1,10);
INSERT INTO OrderLine VALUES(null,7,1,1,10);
INSERT INTO OrderLine VALUES(null,8,1,1,10);
INSERT INTO OrderLine VALUES(null,9,1,1,10);
INSERT INTO OrderLine VALUES(null,10,1,1,10);
INSERT INTO OrderLine VALUES(null,11,1,1,10);
INSERT INTO OrderLine VALUES(null,12,1,1,10);
	
